import "./Day1Module.css";
import { useState, useEffect } from "react";
import { database, auth } from "../src/app/firebase/firebaseconfig";
import { ref, get, update, query } from "firebase/database";

import Topic1 from "./Day4/Topic1";
import Topic2 from "./Day4/Topic2";
import Topic3 from "./Day4/Topic3";
import Topic4 from "./Day4/Topic4";
import Topic5 from "./Day4/Topic5";
import Topic6 from "./Day4/Topic6";
import Topic7 from "./Day4/Topic7";


export default function Day4Module() {
  const [selectedTopic, setSelectedTopic] = useState<number>(1); // Start from Topic 1
  const [completedTopics, setCompletedTopics] = useState<string[]>([]);
  const userId = auth.currentUser?.uid;
  const [UserID, setUserID] = useState<string>("");


  const topics = [
    { id: 1, key: "Topic1", component: <Topic1 /> },
    { id: 2, key: "Topic2", component: <Topic2 /> },
    { id: 3, key: "Topic3", component: <Topic3 /> },
    { id: 4, key: "Topic4", component: <Topic4 /> },
    { id: 5, key: "Topic5", component: <Topic5 /> },
    { id: 6, key: "Topic6", component: <Topic6 /> },
    { id: 7, key: "Topic7", component: <Topic7 /> }
  ];

  useEffect(() => {

    const invitedUsers = sessionStorage.getItem("invitedUsers");
    if(invitedUsers){
      setUserID(invitedUsers);
    }

    if (!userId) return;
    const userProgressRef = ref(database, `userProgress/${userId}/day4/module`);

    get(userProgressRef).then((snapshot) => {
      if (snapshot.exists()) {
        setCompletedTopics(Object.keys(snapshot.val()));
      }
    });
  }, [userId]);

  const selectedTopicIndex = topics.findIndex((topic) => topic.id === selectedTopic);
  const selectedTopicKey = topics[selectedTopicIndex]?.key;
  const selectedTopicContent = topics[selectedTopicIndex]?.component;

  const handleNextTopic = async () => {
    if (!selectedTopicKey || !userId) return;

    const userProgressRef = ref(database, `userProgress/${userId}/day4/module`);

    if (!completedTopics.includes(selectedTopicKey)) {
      await update(userProgressRef, { [selectedTopicKey]: true });
      setCompletedTopics([...completedTopics, selectedTopicKey]);
    }

    if (selectedTopicIndex < topics.length - 1) {
      setSelectedTopic(topics[selectedTopicIndex + 1].id);
    }
  };

  const handlePreviousTopic = () => {
    if (selectedTopicIndex > 0) {
      setSelectedTopic(topics[selectedTopicIndex - 1].id);
    }
  };

  // const markTopicCompleted = async () => {
  //   if (!selectedTopicKey || !userId) return;

  //   const userProgressRef = ref(database, `users/${userId}/progress/Day4`);
  //   await update(userProgressRef, { ["Module"]: true });

  //   setCompletedTopics([...completedTopics, selectedTopicKey]);
  // };


        const markTopicCompleted = async () => {  
          if (!selectedTopicKey || !userId) return;
      
          const UserEmail = sessionStorage.getItem("userEmail");
      
      
                if (UserID) {
                  const usersRef = ref(database, 'invitedUsers');
                  const userQuery = query(usersRef);
            
                  try {
                    const snapshot = await get(userQuery);
                    if (snapshot.exists()) {
                      const userData = snapshot.val();
                      const autoGeneratedId = Object.keys(userData).find(
                        (key) => userData[key].email === UserEmail
                    );
          
                      const userProgressRef = ref(database, `invitedUsers/${autoGeneratedId}/progress/Day4`);
                      await update(userProgressRef, { ["Module"]: true });
            
                    }
                  } catch (error) {
                    console.error("Error fetching user data:", error);
                  }
                }
      
      
          setCompletedTopics([...completedTopics, selectedTopicKey]);
      
          // setCompletionMessage("Let's Go! New Day unlocked...")
        };

  return (
    <div className="Day1-Main">
      <div className="Header">
        <h1 className="h1">Day 4: Research Papers and
        Current Market Position</h1>
      </div>

      <div className="MainContent">
      <div className="Text-Section">

        {selectedTopicContent}
</div>
        <div className="Toggle-Topic">
        {selectedTopicIndex > 0 && (
            <button className="Read-Button-Previous" onClick={handlePreviousTopic}>
              ← Previous Topic
            </button>
          )}

          {selectedTopicIndex < topics.length - 1 ? (
            <button className="Read-Button-Next" onClick={handleNextTopic}>
              {selectedTopicIndex === 0 ? "Let's Get Started →" : "Next Topic →"}
              </button>
          ) : (
            <button className="Read-Button" onClick={markTopicCompleted}>
              ✅ Mark Completed
            </button>
          )}
        </div>
      </div>
    </div>
  );
}