import "./Day1Module.css";
import { useState, useEffect } from "react";
import { database, auth } from "../src/app/firebase/firebaseconfig";
import { ref, get, update, query } from "firebase/database";

import Topic1 from "./Day8/Topic1";



export default function Day8Module() {
  const [selectedTopic, setSelectedTopic] = useState<number>(1); // Start from Topic 1
  const [completedTopics, setCompletedTopics] = useState<string[]>([]);
  const userId = auth.currentUser?.uid;
  const [UserID, setUserID] = useState<string>("");

  const topics = [
    { id: 1, key: "Topic1", component: <Topic1 /> }
  ];

  useEffect(() => {

    const invitedUsers = sessionStorage.getItem("invitedUsers");
    if(invitedUsers){
      setUserID(invitedUsers);
    }

    if (!userId) return;
    const userProgressRef = ref(database, `userProgress/${userId}/day8/module`);

    get(userProgressRef).then((snapshot) => {
      if (snapshot.exists()) {
        setCompletedTopics(Object.keys(snapshot.val()));
      }
    });
  }, [userId]);

  const selectedTopicIndex = topics.findIndex((topic) => topic.id === selectedTopic);
  const selectedTopicKey = topics[selectedTopicIndex]?.key;
  const selectedTopicContent = topics[selectedTopicIndex]?.component;

  const handleNextTopic = async () => {
    if (!selectedTopicKey || !userId) return;

    const userProgressRef = ref(database, `userProgress/${userId}/day8/module`);

    if (!completedTopics.includes(selectedTopicKey)) {
      await update(userProgressRef, { [selectedTopicKey]: true });
      setCompletedTopics([...completedTopics, selectedTopicKey]);
    }

    if (selectedTopicIndex < topics.length - 1) {
      setSelectedTopic(topics[selectedTopicIndex + 1].id);
    }
  };

  const handlePreviousTopic = () => {
    if (selectedTopicIndex > 0) {
      setSelectedTopic(topics[selectedTopicIndex - 1].id);
    }
  };

  // const markTopicCompleted = async () => {
  //   if (!selectedTopicKey || !userId) return;

  //   const userProgressRef = ref(database, `users/${userId}/progress/Day8`);
  //   await update(userProgressRef, { ["Module"]: true });

  //   setCompletedTopics([...completedTopics, selectedTopicKey]);
  // };


                  const markTopicCompleted = async () => {  
                    if (!selectedTopicKey || !userId) return;
                
                    const UserEmail = sessionStorage.getItem("userEmail");
                
                
                          if (UserID) {
                            const usersRef = ref(database, 'invitedUsers');
                            const userQuery = query(usersRef);
                      
                            try {
                              const snapshot = await get(userQuery);
                              if (snapshot.exists()) {
                                const userData = snapshot.val();
                                const autoGeneratedId = Object.keys(userData).find(
                                  (key) => userData[key].email === UserEmail
                              );
                    
                                const userProgressRef = ref(database, `invitedUsers/${autoGeneratedId}/progress/Day8`);
                                await update(userProgressRef, { ["Module"]: true });
                      
                              }
                            } catch (error) {
                              console.error("Error fetching user data:", error);
                            }
                          }
                
                
                    setCompletedTopics([...completedTopics, selectedTopicKey]);
                
                    // setCompletionMessage("Let's Go! New Day unlocked...")
                  };

  return (
    <div className="Day1-Main">
      <div className="Header">
        <h1 className="h1">Day 8: Services Suggestion</h1>
      </div>

      <div className="MainContent">
      <div className="Text-Section">

        {selectedTopicContent}
</div>
        <div className="Toggle-Topic">
        {selectedTopicIndex > 0 && (
            <button className="Read-Button-Previous" onClick={handlePreviousTopic}>
              ← Previous Topic
            </button>
          )}

          {selectedTopicIndex < topics.length - 1 ? (
            <button className="Read-Button-Next" onClick={handleNextTopic}>
              {selectedTopicIndex === 0 ? "Let's Get Started →" : "Next Topic →"}
              </button>
          ) : (
            <button className="Read-Button" onClick={markTopicCompleted}>
              ✅ Mark Completed
            </button>
          )}
        </div>
      </div>
    </div>
  );
}